server:
  port: 8877

datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/boss_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: 864305809

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bosssoft.trainee.entity.dto

